name: 'hello'
description: 'greetings'
inputs:
  who:
    required: false
    default: 'me'
outputs:
  myOutput:
    description: 'output from action'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who }}