name: Github Action Demo
on: [push]
jobs:
  exploring_job:
    runs-on: ububtu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Action from root
        uses: ./
        id: theID
        with:
          who: 'who dat'
      - name: Get the output
        run: echo 'Output - ${{ steps.theID.outputs.myOutput }}'
