name: Github Action Demo
on: [push]
jobs:
  exploring_job:
    runs-on: ubuntu-latest
    steps:
      - name: Use Action from root
        id: theID
        uses: ./
      - name: Get the output
        run: echo 'Output - ${{ steps.theID.outputs.myOutput }}'
